# Generated by Django 4.0.3 on 2022-08-31 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kombat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=250, null=True)),
                ('player2', models.CharField(blank=True, max_length=250, null=True)),
                ('winner', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(blank=True, max_length=250, null=True)),
                ('action', models.CharField(blank=True, max_length=250, null=True)),
                ('damage', models.CharField(blank=True, max_length=250, null=True)),
                ('player1hp', models.CharField(blank=True, max_length=250, null=True)),
                ('player2hp', models.CharField(blank=True, max_length=250, null=True)),
                ('kombat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kombat.kombat')),
            ],
        ),
    ]
