# Generated by Django 4.0.3 on 2022-09-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kombat',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='kombat',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='action',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='damage',
        ),
        migrations.AddField(
            model_name='kombat',
            name='date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='descripcion',
            field=models.CharField(default='Paso el turno', max_length=250),
        ),
        migrations.AddField(
            model_name='turn',
            name='nround',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='turn',
            name='player1hp',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='player2hp',
            field=models.IntegerField(db_index=True),
        ),
    ]
