# Generated by Django 4.0.3 on 2022-09-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0002_remove_kombat_player1_remove_kombat_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='nround',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turn',
            name='player1hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turn',
            name='player2hp',
            field=models.IntegerField(),
        ),
    ]
