# Generated by Django 4.0.3 on 2022-09-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0003_alter_turn_nround_alter_turn_player1hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kombat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
